[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rpg_gpmf"
version = "3.1"
description = "Paket-Fassade fuer rpg_gpmf."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "RalfPeter", email = "ralfpeter.bergheim@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "gpxpy",
    "lxml",
    "numpy",
    "overpy",
    "pandas",
    "pyexiv2",
    "PyYAML",
    "requests",
    "rpg_geo",
    "rpg_gpx",
    "rpg_utils",
    "scipy",
    "tzlocal"
]

[tool.setuptools.packages.find]
where = ["."]
