__title__ = "rpg_gpmf"
__description__ = "Paket-Fassade fuer rpg_gpmf."
__url__ = "[https://github.com/](https://github.com/)RalfPeter/rpg_gpmf"
__version__ = "4.0"
__author__ = "RalfPeter"
__author_email__ = "ralfpeter.bergheim@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2026 RalfPeter"
